System:
  video_file_path: "../data/Colonoscopy/Dataset1/YOS_"
  reference_file_path: "../data/Colonoscopy/Dataset1/ref_mesh.obj"

  optimization_algorithm: 2
  # 0: normal
  # 1: Distance Only
  # 2: Normal with only the vertices as reporjection
  verbose: false

Optimizer:
  max_iteration: 10

Image:
  width: 512
  height: 512
  fx: 107.898111501 #2.162177 
  fy: 107.898111501 #2.162177 
  cx: 256
  cy: 256
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0
  scale: 1

Preprocessing:
  create_mask: false
  brightness_threshold: 0
  width_min: 100
  width_max: 400
  height_min: 100
  height_max: 400
# first 40, then 70, then 60

Visualization:
 width: 1600
 height: 900
 show_only_optimised_part: false
 ShouldRotate: true
 w_uv: 512
 h_uv: 512


GT_Mesh:
  OrientNormalsConsistentTangentPlane: 10
  Poisson_depth: 9
  Poisson_width: 0.1
  simplification: 2000
  threshold: 6

colonoscopy:
  max_number_frames: 59
  only_once: true
  start_id: 0
  gt_path: "../data/Colonoscopy/Dataset1/YOS_depth"

# Hamlyn:
#   FPS: 25
#   multiplier: 30
#   addition: 0.093333
#   modulo: 20
#   gt_path: "../data/HamlynDatasetShort/f7phantom/f7/heartDepthMap_"

Kanade:
  iteration: 10
  width: 70
  height: 70


