
System:
  video_file_path: "../data/phi_SfT/real/S5/rgbs/rgb_"
  reference_file_path: "../data/phi_SfT/real/S5/templates/template_mesh_final_textured.obj"

  optimization_algorithm: 1
  # 0: normal
  # 1: Distance Only
  # 2: Normal with only the vertices as reporjection
  verbose: false

Optimizer:
  max_iteration: 10

Image:
  width: 1280
  height: 720
  fx: 642.789
  fy: 629.999
  cx: 636.409
  cy: 369.856

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

Preprocessing:
  create_mask: false
  brightness_threshold: 0
  width_min: 500
  width_max: 800
  height_min: 500
  height_max: 800
# first 40, then 70, then 60

Visualization:
 width: 1600
 height: 900
 w_uv: 1280
 h_uv: 720
 show_only_optimised_part: false
 ShouldRotate: true


Phi_SfT:
  gt_path: "../data/phi_SfT/real/S5/point_clouds/point_cloud_"
  # simplification: 586
  max_number_frames: 50

Kanade:
  iteration: 10
  width: 100
  height: 80

